"""
Streamlit configuration file
"""
[server]
port = 8501
address = "0.0.0.0"
baseUrlPath = ""

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#2c3e50"
backgroundColor = "#ecf0f1"
secondaryBackgroundColor = "#ffffff"
textColor = "#2c3e50"